version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "type:dependencies"
      - "deps:github actions"
    assignees:
      - Goldmensch
      - Kaktushose
  - package-ecosystem: "gradle"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "gradle"
    labels:
      - "type:dependencies"
      - "deps:java"
    assignees:
      - Kaktushose
      - Goldmensch
