/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "jda-commands"
include("core")
include("guice-extension")
include("jda-commands")
