name: "Setup Java and Gradle"
descriptions: "Sets up java with a specific version and gradle"
runs:
  using: "composite"
  steps:
    - name: Read java version
      id: version
      shell: bash
      run: |
        content=$(cat "gradle.properties")
        regex="java\.version *= * (.*)"
        if [[ $content =~ $regex ]]
        then 
          echo "java=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
        fi
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ steps.version.outputs.java }}
    - uses: gradle/actions/setup-gradle@v4