package io.github.kaktushose.jdac.property;

import dev.goldmensch.propane.IntrospectionSkeleton;
import dev.goldmensch.propane.Scope;
import dev.goldmensch.propane.event.Event;
import dev.goldmensch.propane.event.Listener;
import dev.goldmensch.propane.property.EnumerationPropertySkeleton;
import dev.goldmensch.propane.property.MappingPropertySkeleton;
import dev.goldmensch.propane.property.Property;
import dev.goldmensch.propane.property.PropertyProviderSkeleton;
import dev.goldmensch.propane.property.SingletonPropertySkeleton;
import io.github.kaktushose.jdac.property.events.JDACEvent;
import io.github.kaktushose.jdac.property.internal.JDACIntrospectionImpl;

/// The [JDACIntrospection] type is the central element of the property system.
/// Its purpose is to expose the property and event system to the user.
///
/// Each [IntrospectionSkeleton] instance is bound to a [Scope], allowing accessing the scopes' and its parents'
/// [Properties][Property]. For more information visit the documentation of [Scope]. Unless
/// the root scopes' [IntrospectionSkeleton] instance, each [IntrospectionSkeleton] instance is child of another, inheriting its values
/// that are combines with its own. For more information, visit the section [below](#properties)
///
/// ## Properties
/// An instance of [IntrospectionSkeleton] can hold [PropertyProviderSkeleton]s for all [properties][Property]
/// accessible by its [Scope]. An introspection instance
/// will first compute its own value using the providers registered at it and possibly combine it with the
/// values from the introspection instances' parent(s). For more information on how this is done, visit the documentation of
/// [SingletonPropertySkeleton], [MappingPropertySkeleton] and [EnumerationPropertySkeleton].
///
/// After [computing][PropertyProviderSkeleton] a value, it will be cached for the lifetime of that introspection instance.
/// Accessing such an instance is threadsafe, and it is guaranteed to always return the same instance.
///
/// TODO: docs (scoped access)
///
/// ## Listeners
/// A [Listener] registered on an [IntrospectionSkeleton] instance is stored for the lifetime of this
/// instance. It will be called if the event it is registered for, is either fired in this introspection instance itself
/// or any children of it.
///
/// ```java
/// Introspection A = ...;
/// Introspection B with B is children of A
///
/// A.subscribe(FooEvent.class, _ -> System.out.println("Foo fired"));
///
/// publish FooEvent in A -> "Foo fired" printed
/// publish FooEvent in B -> "Foo fired" printed
///
/// // ---------------------------------------
/// B.subsribe(BarEvent.class, _ -> System.out.println("Bar fired"));
///
/// publish BarEvent in A -> nothing printed
/// publish BarEvent in B -> "Bar fired" printed
///
/// ```
///
/// ## Note on Propane
/// [Propane](https://github.com/Goldmensch/propane) is the underlying library, that JDA-Commands is using for its property system.
/// In most cases, you won't directly access propane but the wrappers around it provided by JDA-Commands
/// like [JDACIntrospection], [JDACProperty] etc. These are generated by propane as specializations
/// of general types like [IntrospectionSkeleton] and [Property]. If you debug your bot or encounter any problems, it may be helpful
/// to visit the documentation or [source code]((https://github.com/Goldmensch/propane)) of Propane.
public interface JDACIntrospection extends IntrospectionSkeleton<JDACIntrospection, JDACScope> {

  /// Returns the value for the requested property by either retrieving it from the cache
  /// or computing it according to the [class' documentation][JDACIntrospection].
  ///
  /// @param specific the requested property
  /// @return the value of the requested property
  /// @see JDACIntrospection JDACIntrospection' class documentation
  <T> T get(JDACProperty<T> specific);

  static boolean accessible() {
    return JDACIntrospectionImpl.INTROSPECTION.isBound();
  }

  static JDACIntrospection accessScoped() {
    return JDACIntrospectionImpl.INTROSPECTION.get();
  }

  static <T> T scopedGet(JDACProperty<T> property) {
    return accessScoped().get(property);
  }

  /// Subscribes to an [event][Event] with the given [Listener].
  /// The provided listener will be stored in this instance, thus be available for the lifetime
  /// of this introspection instance.
  ///
  /// @param listener the [Listener] to be registered
  /// @see JDACIntrospection JDACIntrospection' class documentation
  /// @see JDACEvent
  @Override
  void subscribe(Listener<? extends Event<JDACScope>, JDACScope, JDACIntrospection> listener);
}
