name: Wiki Deploy
on:
  push:
    branches:
      - wiki
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build
      - name: Checkout Docs Branch
        run: |
          git checkout docs
          git pull
      - name: Move Files
        run: |
          rm -rf ./wiki
          mv ./site ./wiki
          rm -rf ./site
      - name: Commit & Push Changes
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add .
          git commit -m "update documentation"
          git push