name: Development Javadocs

on:
  push:
    branches: [ development, main, workflows/docs ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Generate Documentation
        run: |
          mvn javadoc:aggregate
      - name: Find target directory
        id: target_dir
        run: |
          branch=${GITHUB_REF#refs/heads/}
          
          if [ "$branch" == "development" ]; then
            echo "name=development" >> "$GITHUB_OUTPUT"
          elif [ "$branch" == "main" ]; then
            echo "name=latest" >> "$GITHUB_OUTPUT"
          elif [ "$branch" == "workflows/docs" ]; then
            echo 
          fi
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./target/site/apidocs
          branch: docs
          target-folder: javadocs/${{ steps.target_dir.outputs.name }}
