name: Development Javadocs

on:
  push:
    branches:
      - development
      - main
      - 'legacy/*'
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Generate Documentation
        run: |
          gradle javadoc
      - name: Find target directory
        id: target_dir
        run: |
          branch=${GITHUB_REF#refs/heads/}
          
          if [ "$branch" == "development" ]; then
            echo "name=development" >> "$GITHUB_OUTPUT"
          elif [ "$branch" == "main" ]; then
            echo "name=latest" >> "$GITHUB_OUTPUT"
          elif [[ $branch == legacy/* ]]; then
            echo "name=${branch#legacy/}" >> "$GITHUB_OUTPUT"
          else
            echo "name=ignore" >> "$GITHUB_OUTPUT"
          fi
      - name: Deploy docs
        if: ${{ steps.target_dir.outputs.name != 'ignore' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./jda-commands/build/docs/javadoc
          branch: docs
          target-folder: javadocs/${{ steps.target_dir.outputs.name }}
