name: pr.yml
on:
  pull_request_target:

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label pr automatically
        uses: actions/labeler@v5
        with:
          sync-labels: true
