name: Wiki Deployment
on:
  push:
    branches:
      - wiki
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build
      - name: Deploy Wiki
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./site
          branch: docs
          target-folder: wiki/