name: Wiki Deployment
on:
  push:
    branches:
      - wiki
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          git fetch
          git checkout gh-pages
          git branch --set-upstream-to=origin/gh-pages
          git pull
          git checkout wiki
          
          pip install -r requirements.txt
          
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          
          msg="${{ github.event.head_commit.message }}"
          regex="^Release ((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
          
          if [[ $msg =~ $regex ]]
          then
            mike deploy -u ${BASH_REMATCH[1]} wiki
            mike set-default ${BASH_REMATCH[1]}
          else
            mike deploy snapshot
          fi
      - name: Deploy Wiki
        run: |
          git checkout gh-pages
          git push