name: Snapshot Wiki Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          git pull
          
          pip install -r wiki/requirements.txt
          
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          
          cd wiki
          mike deploy snapshot
      - name: Deploy Wiki
        run: |
          git pull
          git push origin gh-pages